# STATISTICAL TEST

## Bivariate analysis of college placement report
## Chi-square testing and Analysis of Variance were implemented on the dataset
## Dataset was sourced from kaggle.com

## By Chidiebere Afamefuna. 

## Chi-square Test

In [1]:
#import libraries
import scipy.stats as stats
import seaborn as sns
import pandas as pd 
import numpy as np

In [2]:
# loading of dataset

data = pd.read_csv('C:\\Users\\USER\Desktop\\classification\\collegePlace.csv')
data.head()

Age  Gender                         Stream  Internships  CGPA  Hostel  \
0   22    Male  Electronics And Communication            1     8       1   
1   21  Female               Computer Science            0     7       1   
2   22  Female         Information Technology            1     6       0   
3   21    Male         Information Technology            0     8       0   
4   22    Male                     Mechanical            0     8       1   

   HistoryOfBacklogs  PlacedOrNot  
0                  1            1  
1                  1            1  
2                  0            1  
3                  1            1  
4                  0            1

In [4]:
# table for Gender and PlaceOrNot
table = pd.crosstab(data['Gender'], data['PlacedOrNot'])
print(table)

PlacedOrNot     0     1
Gender                 
Female        216   275
Male         1111  1364


In [6]:
# observed values

observed_values = table.values
print('observed values:\n {}'.format(observed_values))

observed values:
 [[ 216  275]
 [1111 1364]]


In [7]:
value = stats.chi2_contingency(table)
value

(0.0995364040812469,
 0.7523866780714197,
 1,
 array([[ 219.6753203,  271.3246797],
        [1107.3246797, 1367.6753203]]))

In [8]:
expected_values = value[3]

In [9]:
expected_values

array([[ 219.6753203,  271.3246797],
       [1107.3246797, 1367.6753203]])

In [12]:
# to determine the degree of freedom

rows = len(table.iloc[0:2,])
columns = len(table.iloc[0,0:2])

DOF = (rows-1) * (columns-1)
print('Degree of Freedom: {}'.format(DOF))

Degree of Freedom: 1


In [13]:
from scipy.stats import chi2

chi_square = sum([(o-e)**2/e for o,e in zip(observed_values, expected_values)])
chi_square_stat = chi_square[0] + chi_square[1]

print('chi-square statistics: {}'.format(chi_square_stat))

chi-square statistics: 0.13335130009354274


In [14]:
# critical value

alpha = 0.05
critical_value = chi2.ppf(q=1-alpha, df =DOF)
print('critical_value: {}'.format(critical_value))

critical_value: 3.841458820694124


In [15]:
# p value

p_value = 1 - chi2.cdf(x=chi_square_stat, df=DOF)


In [16]:
print('p-value: {}'.format(p_value))
print('Significance level: {}'.format(alpha))
print('Degree of Freedom: {}'.format(DOF))


p-value: 0.7149822918027116
Significance level: 0.05
Degree of Freedom: 1


In [18]:
# Result Statement

if chi_square_stat >= critical_value:
    print('Reject Null Hypothesis (H0)')
else:
    print('Retain Null Hypothesis (H0)')
    
if p_value <= alpha:
    print('Reject Null Hypothesis (H0)')
else:
    print('Retain Null Hypothesis (H0)')

Retain Null Hypothesis (H0)
Retain Null Hypothesis (H0)


### Conclusion

### This means that theres no relationship between the 'Gender' variable and 'PlacedOrNot' variable.



## ANOVA TEST

In [26]:
import pingouin as pg

In [28]:
AoV = pg.anova(dv ='Age', between = 'PlacedOrNot', data =data, detailed=True)
AoV

Source           SS    DF         MS         F     p-unc       np2
0  PlacedOrNot    11.469527     1  11.469527  6.545894  0.010562  0.002204
1       Within  5193.435732  2964   1.752171       NaN       NaN       NaN

### Conclusion

### As p-value is less than the threshold value of 0.05, the Null hypothesis will be rejected.
### This shows that there's arelationship between 'Age' and 'PlacedOrNot' variables.